stages:
  - build
  - deploy

git pull :
  stage: build
  script:
    - cd /root/eclipse-workspace/skipper
    - git pull

migrate :
  stage: build
  script:
    - cd /root/eclipse-workspace/skipper
    - pwd
    - workon skipper
    - python manage.py migrate

restart service:
  stage: deploy
  script:
    - cd /root/eclipse-workspace/skipper
    - pwd
    - workon skipper
    - ./stop_web.sh && ./start_web.sh
