stages:
  - build
  - deploy

rsync :
  stage: build
  script:
    - cd /root/eclipse-workspace/skipper && git pull

migrate :
  stage: build
  script:
    - workon skipper && python manage.py migrate

restart service:
  stage: deploy
  script:
    - ./stop_web.sh && ./start_web.sh
