stages:
  - build
  - deploy

git pull:
  stage: build
  script:
    - cd /root/eclipse-workspace/skipper
    - git pull

migrate:
  stage: build
  script:
    - cd /root/eclipse-workspace/skipper
    - /root/.virtualenvs/skipper/bin/python manage.py migrate

stop:
  stage: deploy
  script:
    - cd /root/eclipse-workspace/skipper 
    - pkill -f runserver
  allow_failure: true

start:
  stage: deploy
  script:
    - cd /root/eclipse-workspace/skipper 
    - source /root/.virtualenvs/skipper/bin/activate
    - ./start_web.sh
