stages:
  - build
  - deploy

git pull:
  stage: build
  script:
    - cd /root/eclipse-workspace/skstack
    - git pull

migrate:
  stage: build
  script:
    - cd /root/eclipse-workspace/skstack
    - /root/.virtualenvs/skstack/bin/python manage.py migrate

stop:
  stage: deploy
  script:
    - pkill -f runserver
  allow_failure: true

start:
  stage: deploy
  script:
    - cd /root/eclipse-workspace/skstack 
    - source /root/.virtualenvs/skstack/bin/activate
    - setsid ./start_web.sh
