# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-19 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentname', models.CharField(max_length=100, null=True, verbose_name='\u5bf9\u8c61')),
                ('assessmentnum', models.TextField(max_length=2000, null=True, verbose_name='\u6743\u91cd')),
                ('assessmentcontent', models.TextField(max_length=2000, null=True, verbose_name='\u5185\u5bb9')),
                ('assessmenttime', models.CharField(max_length=30, null=True, verbose_name='\u65f6\u95f4')),
                ('recordpersonnel', models.CharField(max_length=30, null=True, verbose_name='\u8bb0\u5f55\u4eba\u5458')),
                ('remarks', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='\u7c7b\u578b')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='\u53d8\u66f4\u4e3b\u9898')),
                ('changetime', models.CharField(max_length=100, null=True, verbose_name='\u53d8\u66f4\u65f6\u95f4')),
                ('operator', models.CharField(max_length=20, null=True, verbose_name='\u64cd\u4f5c\u4eba')),
                ('business', models.CharField(max_length=50, null=True, verbose_name='\u6d89\u53ca\u7684\u4e1a\u52a1')),
                ('content', models.TextField(max_length=2000, null=True, verbose_name='\u64cd\u4f5c\u5185\u5bb9')),
                ('influence', models.CharField(max_length=100, null=True, verbose_name='\u5f71\u54cd\u540e\u679c')),
                ('rollback', models.TextField(blank=True, max_length=2000, null=True, verbose_name='\u56de\u6eda\u6b65\u9aa4')),
                ('recordtime', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8bb0\u5f55\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='\u7cfb\u7edf\u540d\u79f0')),
                ('describe', models.TextField(max_length=2000, null=True, verbose_name='\u95ee\u9898\u63cf\u8ff0')),
                ('solution', models.TextField(max_length=2000, null=True, verbose_name='\u89e3\u51b3\u65b9\u6848')),
                ('developername', models.CharField(max_length=30, null=True, verbose_name='\u7cfb\u7edf\u5f00\u53d1\u4eba\u5458')),
                ('telephone', models.CharField(max_length=30, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('mail', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u90ae\u7bb1')),
            ],
        ),
        migrations.CreateModel(
            name='Faq_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='\u95ee\u9898\u7c7b\u522b')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventitle', models.CharField(max_length=100, null=True, verbose_name='\u6545\u969c\u6807\u9898')),
                ('eventstarttime', models.CharField(max_length=100, null=True, verbose_name='\u6545\u969c\u5f00\u59cb\u65f6\u95f4')),
                ('eventendtime', models.CharField(max_length=100, null=True, verbose_name='\u6545\u969c\u7ed3\u675f\u65f6\u95f4')),
                ('eventpeople', models.CharField(max_length=30, null=True, verbose_name='\u6545\u969c\u8d23\u4efb\u4eba')),
                ('eventproduct', models.CharField(max_length=30, null=True, verbose_name='\u5f71\u54cd\u4ea7\u54c1')),
                ('eventdescribe', models.TextField(max_length=1000, null=True, verbose_name='\u6545\u969c\u63cf\u8ff0')),
                ('eventdispose', models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u6545\u969c\u6539\u8fdb')),
            ],
        ),
        migrations.CreateModel(
            name='Record_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='\u6545\u969c\u7b49\u7ea7')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='eventclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skrecord.Record_list', verbose_name='\u6545\u969c\u7b49\u7ea7'),
        ),
        migrations.AddField(
            model_name='faq',
            name='problemclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skrecord.Faq_list', verbose_name='\u95ee\u9898\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessmentclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skrecord.Assessment_list', verbose_name='\u7c7b\u578b'),
        ),
    ]
