# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-19 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skcmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='* \u544a\u8b66\u5206\u7ec4\u540d\u79f0')),
                ('serial', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='\u5fae\u4fe1\u901a\u9053')),
                ('descrition', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u76d1\u63a7\u8303\u56f4')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weixin_status', models.BooleanField(default=False, verbose_name='\u5fae\u4fe1\u72b6\u6001')),
                ('email_status', models.BooleanField(default=False, verbose_name='\u90ae\u4ef6\u72b6\u6001')),
                ('sms_status', models.BooleanField(default=False, verbose_name='\u77ed\u4fe1\u72b6\u6001')),
                ('dd_status', models.BooleanField(default=False, verbose_name='\u9489\u9489\u72b6\u6001')),
                ('tel_status', models.IntegerField(default=0, verbose_name='\u7535\u8bdd\u72b6\u6001')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skapi.AlarmGroup', verbose_name='\u6240\u5c5e\u5206\u7ec4')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='\u53d1\u9001')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
                ('token', models.CharField(max_length=20, null=True, verbose_name='\u6388\u6743Token')),
                ('type', models.CharField(choices=[(0, '\u5fae\u4fe1'), (1, '\u90ae\u4ef6'), (2, '\u77ed\u4fe1'), (3, '\u7535\u8bdd'), (4, '\u9489\u9489')], max_length=20, null=True, verbose_name='\u7c7b\u578b')),
                ('receiver', models.CharField(max_length=50, null=True, verbose_name='\u63a5\u6536\u4eba')),
                ('serial', models.CharField(max_length=10, null=True, verbose_name='\u5fae\u4fe1\u901a\u9053')),
                ('level', models.CharField(max_length=10, null=True, verbose_name='\u7ea7\u522b')),
                ('subject', models.TextField(max_length=50, null=True, verbose_name='\u6807\u9898')),
                ('content', models.TextField(max_length=200, null=True, verbose_name='\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='* \u544a\u8b66\u6536\u4ef6\u4eba')),
                ('email', models.EmailField(max_length=30, null=True, verbose_name='* \u90ae\u7bb1')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='* \u7535\u8bdd\u53f7\u7801')),
                ('dd', models.CharField(max_length=20, null=True, verbose_name='* \u9489\u9489\u53f7')),
                ('app', models.ManyToManyField(blank=True, to='skcmdb.App', verbose_name='\u6388\u6743APP')),
            ],
        ),
        migrations.CreateModel(
            name='TokenAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='* \u6388\u6743\u7528\u6237')),
                ('token', models.CharField(max_length=20, null=True, verbose_name='* Token')),
                ('descrition', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u9014')),
            ],
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='* \u7b56\u7565\u540d\u79f0')),
                ('weixin_status', models.BooleanField(default=False, verbose_name='\u5fae\u4fe1\u72b6\u6001')),
                ('email_status', models.BooleanField(default=False, verbose_name='\u90ae\u4ef6\u72b6\u6001')),
                ('sms_status', models.BooleanField(default=False, verbose_name='\u77ed\u4fe1\u72b6\u6001')),
                ('dd_status', models.BooleanField(default=False, verbose_name='\u9489\u9489\u72b6\u6001')),
                ('tel_status', models.BooleanField(default=False, verbose_name='\u7535\u8bdd\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='ZabbixRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='\u53d1\u9001\u8005')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u8bb0\u5f55\u65f6\u95f4')),
                ('token', models.CharField(max_length=20, null=True, verbose_name='\u6388\u6743Token')),
                ('appname', models.CharField(max_length=50, null=True, verbose_name='APPNAME')),
                ('subject', models.TextField(max_length=50, null=True, verbose_name='\u6807\u9898')),
                ('status', models.CharField(max_length=30, null=True, verbose_name='\u72b6\u6001')),
                ('host', models.CharField(max_length=30, null=True, verbose_name='\u4e3b\u673a')),
                ('event', models.CharField(max_length=30, null=True, verbose_name='\u4e8b\u4ef6ID')),
                ('content', models.TextField(max_length=200, null=True, verbose_name='\u5185\u5bb9')),
            ],
        ),
        migrations.AddField(
            model_name='alarmuser',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skapi.UserPolicy', verbose_name='\u7528\u6237\u7b56\u7565'),
        ),
        migrations.AddField(
            model_name='alarmlist',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skapi.AlarmUser', verbose_name='\u7f16\u53f7ID'),
        ),
        migrations.AddField(
            model_name='alarmgroup',
            name='user',
            field=models.ManyToManyField(blank=True, to='skapi.AlarmUser', verbose_name='\u544a\u8b66\u540d\u5355'),
        ),
    ]
