# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-19 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skcmdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField(choices=[(0, '\u5e94\u7528\u8fd0\u7ef4'), (1, '\u7cfb\u7edf\u8fd0\u7ef4'), (2, '\u57fa\u7840\u8fd0\u7ef4'), (3, 'dba\u8fd0\u7ef4'), (4, 'IT\u652f\u6301')], null=True, verbose_name='\u8fd0\u7ef4\u89d2\u8272')),
                ('iphone', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('jobclass', models.CharField(max_length=20, verbose_name='\u8fd0\u7ef4\u7cfb\u7edf\u5206\u5de5')),
                ('jobuse', models.CharField(max_length=15, verbose_name='\u8fd0\u7ef4\u5de5\u5177')),
                ('businessline', models.ManyToManyField(to='skcmdb.YwGroup')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nicknames', to=settings.AUTH_USER_MODEL)),
                ('secondaryname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nickname_backup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=15, verbose_name='\u7b49\u7ea7')),
                ('responsetime', models.CharField(max_length=15, verbose_name='\u54cd\u5e94\u65f6\u95f4')),
                ('processingpersonnel', models.CharField(max_length=15, verbose_name='\u8ddf\u8fdb\u4eba\u5458')),
                ('event', models.CharField(max_length=200, verbose_name='\u5904\u7406\u95ee\u9898\u548c\u5347\u7ea7\u6d41\u7a0b')),
                ('participant', models.CharField(max_length=15, verbose_name='\u53c2\u4e0e\u4eba\u5458')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(max_length=200, verbose_name='\u516c\u544a\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=15, verbose_name='\u5e73\u53f0\u540d\u79f0')),
                ('platform_url', models.URLField(max_length=60, verbose_name='\u5e73\u53f0url')),
            ],
        ),
        migrations.CreateModel(
            name='PlatFormclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_class', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u5e73\u53f0\u5206\u7c7b')),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], verbose_name='\u662f\u5426\u8f6e\u503c')),
                ('emergency_contact', models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], verbose_name='\u662f\u5426\u4e3a\u91cd\u8981\u8054\u7cfb\u4eba')),
                ('rota_number', models.CharField(max_length=15, null=True, verbose_name='\u503c\u73ed\u987a\u5e8f')),
                ('iphone_rota', models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], verbose_name='\u662f\u5426\u7535\u8bdd\u503c\u73ed')),
                ('iphone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_iphone', to='skyw.Devops')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rota_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_class',
            field=models.ManyToManyField(blank=True, to='skyw.PlatFormclass'),
        ),
    ]
