# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-19 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformclass',
            name='platform_class',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u5e73\u53f0\u5206\u7c7b'),
        ),
    ]
