# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-19 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0002_auto_20171019_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_class',
            field=models.ManyToManyField(blank=True, to='skyw.PlatFormclass'),
        ),
    ]
