# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-20 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skyw', '0003_auto_20171019_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='days',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='iphone',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='rota_name',
        ),
        migrations.AddField(
            model_name='rota',
            name='rota_name',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
