# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0004_auto_20171020_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='days',
            field=models.CharField(default=2, max_length=15, verbose_name='\u503c\u73ed\u5929'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rota',
            name='iphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_iphone', to='skyw.Devops'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='rota_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='rota_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
