# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skyw', '0006_auto_20171023_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='dba_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dba_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
