# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0007_rota_dba_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='iphone',
            new_name='rota_iphone',
        ),
        migrations.AddField(
            model_name='rota',
            name='dba_iphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dba_iphone', to='skyw.Devops'),
        ),
    ]
