# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-23 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0008_auto_20171023_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='days',
        ),
    ]
