# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0009_remove_rota_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='spell',
            field=models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], null=True, verbose_name='\u662f\u5426\u8f6e\u503c'),
        ),
    ]
