# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0010_rota_spell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='rota_iphone',
            new_name='iphone',
        ),
        migrations.RenameField(
            model_name='rota',
            old_name='rota_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='dba_iphone',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='dba_name',
        ),
    ]
