# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0011_auto_20171025_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_job', to='skyw.Devops'),
        ),
    ]
