# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0013_remove_rota_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rota_name', to='skyw.Devops'),
        ),
    ]
