# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0014_auto_20171025_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rota_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
