# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-27 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyw', '0015_auto_20171025_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='emergency_contact',
            field=models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], default=1, verbose_name='\u662f\u5426\u4e3a\u91cd\u8981\u8054\u7cfb\u4eba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rota',
            name='iphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_iphone', to='skyw.Devops'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rota_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rota',
            name='spell',
            field=models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], verbose_name='\u662f\u5426\u8f6e\u503c'),
        ),
    ]
