# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='extravars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u53d8\u91cf\u7ec4\u540d')),
                ('vars', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u914d\u7f6e\u53c2\u6570')),
                ('online_status', models.CharField(blank=True, choices=[(b'0', '\u505c\u7528'), (b'1', '\u6fc0\u6d3b')], max_length=30, null=True, verbose_name='\u6fc0\u6d3b\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=50, verbose_name='\u767b\u5f55\u7528\u6237')),
                ('src_ip', models.CharField(max_length=50, verbose_name='\u6765\u6e90ip')),
                ('task_name', models.CharField(default='none', max_length=50, verbose_name='\u4efb\u52a1\u7c7b\u578b')),
                ('time_task_start', models.DateTimeField(null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('time_task_finished', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('cmd_object', models.CharField(max_length=50, null=True, verbose_name='\u64cd\u4f5c\u5bf9\u8c61')),
                ('cmd', models.CharField(max_length=50, verbose_name='\u6267\u884c\u547d\u4ee4')),
                ('cmd_result', models.CharField(max_length=10, verbose_name='\u547d\u4ee4\u7ed3\u679c')),
                ('cmd_detail', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u547d\u4ee4\u7ed3\u679c')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u4f5c\u4e1a\u540d')),
                ('playbook', models.CharField(blank=True, max_length=100, null=True, verbose_name='playbook')),
                ('online_status', models.CharField(blank=True, choices=[(b'0', '\u505c\u7528'), (b'1', '\u6fc0\u6d3b')], max_length=30, null=True, verbose_name='\u6fc0\u6d3b\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d')),
                ('path', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u8def\u5f84')),
                ('online_status', models.CharField(blank=True, choices=[(b'0', '\u505c\u7528'), (b'1', '\u6fc0\u6d3b')], max_length=30, null=True, verbose_name='\u6fc0\u6d3b\u72b6\u6001')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sktask.project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='extravars',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sktask.job', verbose_name='\u6240\u5c5e\u4f5c\u4e1a'),
        ),
    ]
