# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-06 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sktask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='cmd',
            field=models.CharField(max_length=200, verbose_name='\u6267\u884c\u547d\u4ee4'),
        ),
        migrations.AlterField(
            model_name='history',
            name='cmd_detail',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u7ed3\u679c\u8be6\u60c5'),
        ),
    ]
